export const ContentList = [
  {
    id: 1,
    title: 'Batik Parang Motif Barong',
    info: '\t\tBatik Parang motif Barong adalah salah satu varian motif dalam batik Parang yang terinspirasi oleh Barong, makhluk mitologis dalam budaya Jawa. Motif ini menggabungkan garis-garis diagonal khas batik Parang dengan hiasan daun, bunga, dan bentuk lain yang menyerupai Barong. \n\n\t\tBarong adalah sosok mitos yang dianggap sebagai simbol kebaikan dan perlindungan dalam budaya Jawa. Motif Barong dalam batik Parang sering diartikan sebagai representasi keberanian dan kekuatan.',
    createdAt: 'Aug 18, 2023',
    category: 'Parang',
    location: 'Yogyakarta ',
    totalLikes:5800,
    image: require('./src/assets/img/parang-barong.jpg'),
  },
  {
    id: 2,
    title: 'Batik Cuwiri',
    info: '\t\tMotif batik cuwiri berasal dari Surakarta dan Yogjakarta, namun ada juga beberapa daerah yang mengembangkannya. Kata cuwiri berasal dari bahasa Sansekerta yang secara harfiah bermakna kecil-kecil. Motif ini memiliki ornamen berbentuk lengkungan menyerupai gunung yang disebut "meru". \n\n\t\tDengan memakai batik motif cuwiri, harapannya adalah pemakainya terlihat pantas, harmonis, serta dihormati oleh sesamanya. Juga bermakna kemakmuran dan kebaikan. Motif ini juga melambangkan bahwa kehidupan manusia berasal dari nol, mulai dari bayi sampai dengan dewasa. Hal yang sama juga terdapat pada rezeki, berawal dari nol hingga bisa meraih kemakmuran.',
    createdAt: 'May 10, 2023',
    category: 'Cuwiri',
    location: 'Surakarta ',
    totalLikes:1500,
    image: require('./src/assets/img/cuwiri.jpg'),
  },
  {
    id: 3,
    title: 'Batik Sekar Jagad',
    info: '\t\t"Sekar Jagad" dalam bahasa Jawa berarti bunga dunia, dan motif ini mencerminkan keindahan dan keberagaman dunia yang diwakili melalui gambaran bunga-bunga yang bermekaran. \n\n\t\tMotif ini biasanya menampilkan pola bunga yang teratur dan simetris, menciptakan tampilan yang harmonis dan indah. Bunga-bunga dalam batik Sekar Jagad sering diatur secara geometris, menciptakan kesan keteraturan dan keseimbangan dalam desain. Warna-warna yang digunakan dalam motif ini juga cenderung cerah dan mencolok, menambahkan keindahan visual pada kain batik. \n\n\t\tSelain keindahan estetika, batik Sekar Jagad juga memiliki makna filosofis yang mendalam, mencerminkan harmoni dan keselarasan dalam kehidupan. Motif ini menjadi salah satu pilihan yang populer dalam dunia batik, menggambarkan kekayaan seni dan kreativitas warisan budaya Indonesia.',
    createdAt: 'Sep 26, 2023',
    category: 'Sekar Jagad',
    location: 'Jawa Tengah ',
    totalLikes:2300,
    image: require('./src/assets/img/sekar-jagad.jpg'),
  },
  {
    id: 4,
    title: 'Batik Lasem Motif Phoenix',
    info: '\t\tBatik Lasem motif Phoenix adalah salah satu varian batik tradisional yang berasal dari Lasem, Jawa Tengah, Indonesia. Motif ini terinspirasi oleh legenda burung Fenghuang atau Phoenix dalam budaya Tionghoa. Fenghuang dianggap sebagai simbol keberuntungan, keberlanjutan, dan keindahan dalam mitologi Tionghoa. \n\n\t\tMotif ini sering diaplikasikan dengan penuh rincian dan kehalusan, menciptakan tampilan batik yang elegan dan artistik. Motif Phoenix dalam batik Lasem sering digunakan dalam berbagai kegiatan adat, upacara pernikahan, atau acara-acara khusus yang merayakan kemakmuran dan keharmonisan. ',
    createdAt: 'Sep 02, 2023',
    category: 'Lasem',
    location: 'Jawa Tengah',
    totalLikes:3110,
    image: require('./src/assets/img/lasem-phoenix.jpg'),
  },
  {
    id: 5,
    title: 'Batik Sogan Motif Pamiluto',
    info: '\t\tMotif ini sering menggambarkan gambar-gambar hewan seperti burung atau kupu-kupu dalam desain batik. Pamiluto sendiri dapat diartikan sebagai gambaran atau ilustrasi dari berbagai jenis binatang. Motif Pamiluto dalam batik Sogan menambahkan elemen hewan ke dalam desain, menciptakan tampilan yang artistik dan penuh makna. Pemilihan warna dalam batik Sogan motif Pamiluto biasanya cenderung ke arah warna coklat atau keemasan, yang dihasilkan dari zat pewarna alam yang disebut soga. \n\n\t\tMotif Pamiluto dalam batik Sogan seringkali dipahami sebagai simbol keberuntungan, kehidupan, dan keindahan alam. Kombinasi antara kekayaan motif binatang dan estetika khas batik Sogan memberikan nilai budaya dan estetika yang tinggi pada kain batik ini.',
    createdAt: 'May 12, 2023',
    category: 'Sogan',
    location: 'Solo ',
    totalLikes:2600,
    image: require('./src/assets/img/sogan-pamiluto.jpg'),
  },
  {
    id: 6,
    title: 'Batik Megamendung Motif Bunga',
    info: '\t\tMegamendung adalah motif batik khas Cirebon yang terkenal dengan pola awan mendung yang meliuk-liuk dan simetris. Batik Megamendung motif bunga adalah varian batik Megamendung yang menggabungkan motif tradisional Megamendung dengan elemen-elemen bunga. Motif bunga dalam batik Megamendung dapat mencakup berbagai jenis bunga, seperti mawar, teratai, atau bunga lokal lainnya. Bunga-bunga ini ditempatkan di antara atau di sekitar pola awan mendung, menciptakan tampilan yang menarik dan harmonis. \n\n\t\tKombinasi antara elemen tradisional Megamendung dan keindahan motif bunga menciptakan batik yang estetis dan kaya akan simbolisme. Batik ini sering dipandang sebagai representasi harmoni antara langit dan bumi, serta keindahan alam yang dihiasi dengan elemen-elemen bunga yang melambangkan kehidupan dan keberuntungan.',
    createdAt: 'Feb 18, 2023',
    category: 'Megamendung',
    location: 'Cirebon ',
    totalLikes:3200,
    image: require('./src/assets/img/megamendung-bunga.jpg'),
  },
];

export const KategoriList = [
  {
    id: 1,
    title: 'Batik Parang',
    info: 'Motif batik ini memiliki ciri khas berupa garis-garis diagonal berulang yang membentuk pola berliku seperti parang (golok atau pedang). Motif ini sering dihubungkan dengan simbol-simbol seperti kekuatan, keberanian, dan ketabahan. ',
    image: require('./src/assets/img/parang1.jpg'),
  },
  {
    id: 2,
    title: 'Batik Lasem',
    info: 'Batik Lasem adalah gaya batik yang berasal dari Lasem, sebuah kota di Jawa Tengah, Indonesia. Motifnya dikenal dengan berbagai perpaduan warna, termasuk merah, hitam, dan kuning. Batik Lasem sering memiliki pola geometris seperti bunga, burung, dan hewan.',
    image: require('./src/assets/img/lasem.jpg'),
  },
  {
    id: 3,
    title: 'Batik Sogan',
    info: 'Batik Sogan adalah jenis batik yang menggunakan warna cokelat muda, atau "sogan," sebagai warna dasarnya. Motif-motifnya sering menggambarkan alam, seperti bunga, daun, dan binatang.',
    image: require('./src/assets/img/sogan.jpg'),
  },
  {
    id: 4,
    title: 'Batik Megamendung',
    info: 'Batik Megamendung adalah batik khas dari daerah Cirebon, Jawa Barat. Motifnya menggambarkan awan atau mendung di atas langit biru. Batik ini sering diwarnai dengan warna-warna cerah, seperti biru dan merah.',
    image: require('./src/assets/img/megamendung.jpg'),
  },
  {
    id: 5,
    title: 'Batik Tujuh Rupa',
    info: 'Batik Tujuh Rupa adalah batik yang menampilkan tujuh jenis motif berbeda dalam satu kain. Setiap motif mewakili makna dan simbolisasi tertentu. Ini adalah salah satu bentuk batik yang lebih kaya makna.',
    image: require('./src/assets/img/tujuh-rupa.jpg'),
  },
  {
    id: 6,
    title: 'Batik Kawung',
    info: 'Batik Kawung memiliki motif geometris sederhana, biasanya berbentuk lingkaran yang mengelilingi titik tengah. Ini adalah salah satu motif batik tertua dan simbolik dalam budaya Jawa, sering digunakan dalam upacara keagamaan atau kerajaan.',
    image: require('./src/assets/img/kawung.jpg'),
  },
];

export const ProfileData = {
  profilePict: require('./src/assets/img/cat.jpg'),
  name: 'Ilham MP',
  email: 'gorengpisang196@gmail.com',
};